### PR TITLE
Added some more Devious Devices for the AI to use

### PR DESCRIPTION
**Pull request by crazyduck33**

### CODE REVIEW

**Comment by MinLL** [comment]
Can you fix the diffs? Every single line shows as changed in every file, so I can't tell what you changed here.

**Comment by crazyduck33** [comment]
> Can you fix the diffs? Every single line shows as changed in every file, so I can't tell what you changed here.

to be honest i have no idea why it show as diif a complete new file if you have a idea how this could happen ii´m, happy for every hint, The stuff i changed is in the psc file line 701 - 721 and line 162 - 175 and in the PHP its line 195 - 301 and 302 -313

**Comment by MinLL** [comment]
> > Can you fix the diffs? Every single line shows as changed in every file, so I can't tell what you changed here.
> 
> to be honest i have no idea why it show as diif a complete new file if you have a idea how this could happen ii´m, happy for every hint, The stuff i changed is in the psc file line 701 - 721 and line 162 - 175 and in the PHP its line 195 - 301 and 302 -313

I would guess that whatever editor you're using changed the return type on every line.

**Comment by crazyduck33** [comment]
> > > Can you fix the diffs? Every single line shows as changed in every file, so I can't tell what you changed here.
> > 
> > 
> > to be honest i have no idea why it show as diif a complete new file if you have a idea how this could happen ii´m, happy for every hint, The stuff i changed is in the psc file line 701 - 721 and line 162 - 175 and in the PHP its line 195 - 301 and 302 -313
> 
> I would guess that whatever editor you're using changed the return type on every line.

hm  ok will do the change again using a different editor, i used the notepad++ plugin for psc scripts and to edit the php file

**Comment by MinLL** [comment]
> > > > Can you fix the diffs? Every single line shows as changed in every file, so I can't tell what you changed here.
> > > 
> > > 
> > > to be honest i have no idea why it show as diif a complete new file if you have a idea how this could happen ii´m, happy for every hint, The stuff i changed is in the psc file line 701 - 721 and line 162 - 175 and in the PHP its line 195 - 301 and 302 -313
> > 
> > 
> > I would guess that whatever editor you're using changed the return type on every line.
> 
> hm ok will do the change again using a different editor, i used the notepad++ plugin for psc scripts and to edit the php file

Hmmm, I know of other contributors using notepad++ for this. What Git client are you using? Try GitKraken. It might be changing the lines.

**Comment by crazyduck33** [comment]
small update, i coudl fix this issue currently i try to fix a small bug with uneqipping the binder the ai send the command but the armbinder is not removed , need to check tomorrow if its a incompatibility with unforgiving devices cause i could see in papyrus log that unforgiving devices was giving out errors at the same time.

**Comment by crazyduck33** [comment]
Ok the psc file shoudl now only show the changes , but it seems i used a older version of the psc file as the current one as there are some changes not added you already had changed, but as far as i could tell it was only 2 or 3 lines you had changed before

**Comment by crazyduck33** [comment]
i will do another pull request as this one got really messy

**Pull request closed without merging**
